on: 
  issue_comment: 
    types: [created]
    
name: Commands

jobs:  
  urlchecks:
    if: startsWith(github.event.comment.body, '/check-urls')
    name: check-urls
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
      
    - name: list files
      run: |
          PR=$(jq --raw-output .pull_request.number "${GITHUB_EVENT_PATH}")
          files=$(curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/pulls/$PR/files \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Accept: application/vnd.github.antiope-preview+json' \
          --header 'content-type: application/json' | jq --raw-output .[].filename | sed 's/^\|$/"/g'|paste -sd, - | tr -d \" | tr -d \') 
          echo "::set-env name=files::$files"
          
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.2.0
      with:
        save: "urls.csv"
        include_files: ${{ env.files }}
        print_all: true
        
    - name: Archive URL checking results
      if: failure()
      uses: actions/upload-artifact@v2-preview
      with:
        name: urlchecker-results
        path: urls.csv


