name: PR URL checks
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    
    - name: list files
      run: |
        PR=$(jq --raw-output .pull_request.head.ref "${GITHUB_EVENT_PATH}")
        $PR
        git merge-base origin/$PR origin/master
