name: PR URL checks
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2          
    
    - name: list files
      run: |
        PR=$(jq --raw-output .pull_request.head.ref "${GITHUB_EVENT_PATH}")
        files=$(git diff --name-only origin/$PR `git merge-base origin/$PR origin/master` | sed 's/^\|$/"/g'|paste -sd, -)
        echo "::set-env name=files::$files"

        
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@0.2.0
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md
        save: "urls.csv"
        files: ${{ env.files }}
    
    - name: Archive URL checking results
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
        name: urlchecker-results
        path: urls.csv
