name: PR URL checks
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2 
    - name: list files
      run: |
        git branch -a
        PR=$(jq --raw-output .pull_request.head.ref "${GITHUB_EVENT_PATH}")
        git merge-base origin/$PR origin/master
