name: PR URL checks
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2          
    
    - name: list files
      run: |
        PR=$(jq --raw-output .pull_request.head.ref "${GITHUB_EVENT_PATH}")
        git status
        git remote -v
        git merge-base $PR master
